### ISSUE TITLE
Connection Issues

### ISSUE THREAD

**Issue by tomrade** [logstash-plugins/logstash-input-elasticsearch#12]
Ive recently be attempting to use the newer version of this plugin for the metadata support for reindexing. When I run logstash it runs for a while before displaying a "connection refused" faraday error. I'm assuming its retrying/timing out  It could be related to my ES setup but I can run logstash 1.4.2 with its older version of the plugin fine. I also tried backporting the current plugin version to 1.4.2 and got the same error.

Setup
SIngle host with both logstash and ES
Elasticsearch 1.4.4
Logstash 1.5rc2

config
input {
elasticsearch {
hosts => ["localhost"]
docinfo => true
index => "alerts-*"
query => "*"
}

filter {
}

output {
stdout{
codec => "rubydebug"
}
}

Error from verbose output (-vv)
A plugin had an unrecoverable error. Will restart this plugin.
  Plugin: <LogStash::Inputs::Elasticsearch hosts=>[{:host=>"localhost", :port=>9200, :protocol=>"http"}], index=>"alerts-*", query=>"*", scroll=>"1m", docinfo_target=>"@metadata", docinfo_fields=>["_index", "_type", "_id"]>
  Error: Connection refused - Connection refused
  Exception: Faraday::ConnectionFailed
  Stack: org/jruby/ext/socket/RubyTCPSocket.java:126:in `initialize'
org/jruby/RubyIO.java:1177:in `open'
/home/admin/logstash1.5/vendor/jruby/lib/ruby/1.9/net/http.rb:763:in `connect'
org/jruby/ext/timeout/Timeout.java:104:in `timeout'
/home/admin/logstash1.5/vendor/jruby/lib/ruby/1.9/net/http.rb:763:in `connect'
/home/admin/logstash1.5/vendor/jruby/lib/ruby/1.9/net/http.rb:756:in `do_start'
/home/admin/logstash1.5/vendor/jruby/lib/ruby/1.9/net/http.rb:745:in `start'
/home/admin/logstash1.5/vendor/jruby/lib/ruby/1.9/net/http.rb:1293:in `request'
/home/admin/logstash1.5/vendor/bundle/jruby/1.9/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:82:in `perform_request'
/home/admin/logstash1.5/vendor/bundle/jruby/1.9/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:40:in `call'
/home/admin/logstash1.5/vendor/bundle/jruby/1.9/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
/home/admin/logstash1.5/vendor/bundle/jruby/1.9/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:32:in `call'
/home/admin/logstash1.5/vendor/bundle/jruby/1.9/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
/home/admin/logstash1.5/vendor/bundle/jruby/1.9/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
/home/admin/logstash1.5/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.7/lib/elasticsearch/transport/transport/http/faraday.rb:24:in `perform_request'
org/jruby/RubyProc.java:271:in `call'
/home/admin/logstash1.5/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.7/lib/elasticsearch/transport/transport/base.rb:187:in `perform_request'
/home/admin/logstash1.5/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.7/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
/home/admin/logstash1.5/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.7/lib/elasticsearch/transport/client.rb:115:in `perform_request'
/home/admin/logstash1.5/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.7/lib/elasticsearch/api/actions/search.rb:159:in `search'
/home/admin/logstash1.5/vendor/bundle/jruby/1.9/gems/logstash-input-elasticsearch-0.1.4/lib/logstash/inputs/elasticsearch.rb:146:in `run'
/home/admin/logstash1.5/lib/logstash/pipeline.rb:174:in `inputworker'
/home/admin/logstash1.5/lib/logstash/pipeline.rb:168:in `start_input' {:level=>:error, :file=>"logstash/pipeline.rb", :line=>"179", :method=>"inputworker"'}

**Comment by tomrade** [comment]
could this be proxy related. I have proxy environmental set but an exception set for localhost. Since the issue occurs using the latest plugin in both logstash 1.4.2 and 1.5rc2 is it related to how the plugin makes the es http request?

**Comment by tomrade** [comment]
Fixed the issue, It was proxy related. Although I had a "no-proxy" env variable for localhost, it was still attempting to use the system proxy for the HTTP request to localhost
