### ISSUE TITLE
basic config not working in 1.5.0?

### ISSUE THREAD

**Issue by nellicus** [logstash-plugins/logstash-input-elasticsearch#16]
Not sure if I'm missing anything here, from the docs this should work

config

```
abonuccelli@w530 /opt/elk/TEST/logstash-1.5.0 $ cat config/test.conf 
input { 
    elasticsearch {  
            hosts => "w530" 
            port => "9203"
            index => "test"
    } 
}
filter {
}
output {
    stdout{ codec=>rubydebug }
}
```

run

```
abonuccelli@w530 /opt/elk/TEST/logstash-1.5.0 $ ./bin/logstash -f config/9661.conf  --debug
Reading config file {:file=>"logstash/agent.rb", :level=>:debug, :line=>"293", :method=>"local_config"}
Compiled pipeline code:
        @inputs = []
        @filters = []
        @outputs = []
        @periodic_flushers = []
        @shutdown_flushers = []

          @input_elasticsearch_1 = plugin("input", "elasticsearch", LogStash::Util.hash_merge_many({ "hosts" => ("w530") }, { "port" => ("9203") }))

          @inputs << @input_elasticsearch_1


          @output_stdout_2 = plugin("output", "stdout", LogStash::Util.hash_merge_many({ "codec" => ("rubydebug") }))

          @outputs << @output_stdout_2

  def filter_func(event)
    events = [event]
    @logger.debug? && @logger.debug("filter received", :event => event.to_hash)

    events
  end
  def output_func(event)
    @logger.debug? && @logger.debug("output received", :event => event.to_hash)
    @output_stdout_2.handle(event)

  end {:level=>:debug, :file=>"logstash/pipeline.rb", :line=>"28", :method=>"initialize"}
Plugin not defined in namespace, checking for plugin file {:type=>"input", :name=>"elasticsearch", :path=>"logstash/inputs/elasticsearch", :level=>:debug, :file=>"logstash/plugin.rb", :line=>"133", :method=>"lookup"}
Using version 0.1.x input plugin 'elasticsearch'. This plugin isn't well supported by the community and likely has no maintainer. {:level=>:info, :file=>"logstash/config/mixin.rb", :line=>"223", :method=>"print_version_notice"}
Plugin not defined in namespace, checking for plugin file {:type=>"codec", :name=>"json", :path=>"logstash/codecs/json", :level=>:debug, :file=>"logstash/plugin.rb", :line=>"133", :method=>"lookup"}
Using version 0.1.x codec plugin 'json'. This plugin isn't well supported by the community and likely has no maintainer. {:level=>:info, :file=>"logstash/config/mixin.rb", :line=>"223", :method=>"print_version_notice"}
config LogStash::Codecs::JSON/@charset = "UTF-8" {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"112", :method=>"config_init"}
config LogStash::Inputs::Elasticsearch/@hosts = ["w530"] {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"112", :method=>"config_init"}
config LogStash::Inputs::Elasticsearch/@port = 9203 {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"112", :method=>"config_init"}
config LogStash::Inputs::Elasticsearch/@debug = false {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"112", :method=>"config_init"}
config LogStash::Inputs::Elasticsearch/@codec = <LogStash::Codecs::JSON charset=>"UTF-8"> {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"112", :method=>"config_init"}
config LogStash::Inputs::Elasticsearch/@add_field = {} {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"112", :method=>"config_init"}
config LogStash::Inputs::Elasticsearch/@index = "logstash-*" {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"112", :method=>"config_init"}
config LogStash::Inputs::Elasticsearch/@query = "{\"query\": { \"match_all\": {} } }" {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"112", :method=>"config_init"}
config LogStash::Inputs::Elasticsearch/@scan = true {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"112", :method=>"config_init"}
config LogStash::Inputs::Elasticsearch/@size = 1000 {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"112", :method=>"config_init"}
config LogStash::Inputs::Elasticsearch/@scroll = "1m" {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"112", :method=>"config_init"}
config LogStash::Inputs::Elasticsearch/@docinfo = false {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"112", :method=>"config_init"}
config LogStash::Inputs::Elasticsearch/@docinfo_target = "@metadata" {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"112", :method=>"config_init"}
config LogStash::Inputs::Elasticsearch/@docinfo_fields = ["_index", "_type", "_id"] {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"112", :method=>"config_init"}
config LogStash::Inputs::Elasticsearch/@ssl = false {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"112", :method=>"config_init"}
Plugin not defined in namespace, checking for plugin file {:type=>"output", :name=>"stdout", :path=>"logstash/outputs/stdout", :level=>:debug, :file=>"logstash/plugin.rb", :line=>"133", :method=>"lookup"}
Using version 0.1.x output plugin 'stdout'. This plugin isn't well supported by the community and likely has no maintainer. {:level=>:info, :file=>"logstash/config/mixin.rb", :line=>"223", :method=>"print_version_notice"}
Plugin not defined in namespace, checking for plugin file {:type=>"codec", :name=>"rubydebug", :path=>"logstash/codecs/rubydebug", :level=>:debug, :file=>"logstash/plugin.rb", :line=>"133", :method=>"lookup"}
Using version 0.1.x codec plugin 'rubydebug'. This plugin isn't well supported by the community and likely has no maintainer. {:level=>:info, :file=>"logstash/config/mixin.rb", :line=>"223", :method=>"print_version_notice"}
config LogStash::Codecs::RubyDebug/@metadata = false {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"112", :method=>"config_init"}
config LogStash::Outputs::Stdout/@codec = <LogStash::Codecs::RubyDebug > {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"112", :method=>"config_init"}
config LogStash::Outputs::Stdout/@type = "" {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"112", :method=>"config_init"}
config LogStash::Outputs::Stdout/@tags = [] {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"112", :method=>"config_init"}
config LogStash::Outputs::Stdout/@exclude_tags = [] {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"112", :method=>"config_init"}
config LogStash::Outputs::Stdout/@workers = 1 {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"112", :method=>"config_init"}
Pipeline started {:level=>:info, :file=>"logstash/pipeline.rb", :line=>"86", :method=>"run"}
Logstash startup completed
A plugin had an unrecoverable error. Will restart this plugin.
  Plugin: <LogStash::Inputs::Elasticsearch hosts=>[{:host=>"w530", :port=>9200, :protocol=>"http"}], index=>"logstash-*", query=>"{\"query\": { \"match_all\": {} } }", scroll=>"1m", docinfo_target=>"@metadata", docinfo_fields=>["_index", "_type", "_id"]>
  Error: Connection reset by peer - Connection reset by peer
  Exception: Faraday::ConnectionFailed
  Stack: org/jruby/RubyIO.java:2858:in `read_nonblock'
/opt/elk/TEST/logstash-1.5.0/vendor/jruby/lib/ruby/1.9/net/protocol.rb:141:in `rbuf_fill'
/opt/elk/TEST/logstash-1.5.0/vendor/jruby/lib/ruby/1.9/net/protocol.rb:122:in `readuntil'
/opt/elk/TEST/logstash-1.5.0/vendor/jruby/lib/ruby/1.9/net/protocol.rb:132:in `readline'
/opt/elk/TEST/logstash-1.5.0/vendor/jruby/lib/ruby/1.9/net/http.rb:2571:in `read_status_line'
/opt/elk/TEST/logstash-1.5.0/vendor/jruby/lib/ruby/1.9/net/http.rb:2560:in `read_new'
/opt/elk/TEST/logstash-1.5.0/vendor/jruby/lib/ruby/1.9/net/http.rb:1328:in `transport_request'
org/jruby/RubyKernel.java:1270:in `catch'
/opt/elk/TEST/logstash-1.5.0/vendor/jruby/lib/ruby/1.9/net/http.rb:1325:in `transport_request'
/opt/elk/TEST/logstash-1.5.0/vendor/jruby/lib/ruby/1.9/net/http.rb:1302:in `request'
/opt/elk/TEST/logstash-1.5.0/vendor/jruby/lib/ruby/1.9/net/http.rb:1295:in `request'
/opt/elk/TEST/logstash-1.5.0/vendor/jruby/lib/ruby/1.9/net/http.rb:746:in `start'
/opt/elk/TEST/logstash-1.5.0/vendor/jruby/lib/ruby/1.9/net/http.rb:1293:in `request'
/opt/elk/TEST/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:82:in `perform_request'
/opt/elk/TEST/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:40:in `call'
/opt/elk/TEST/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
/opt/elk/TEST/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:32:in `call'
/opt/elk/TEST/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
/opt/elk/TEST/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
/opt/elk/TEST/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.7/lib/elasticsearch/transport/transport/http/faraday.rb:24:in `perform_request'
org/jruby/RubyProc.java:271:in `call'
/opt/elk/TEST/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.7/lib/elasticsearch/transport/transport/base.rb:187:in `perform_request'
/opt/elk/TEST/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.7/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
/opt/elk/TEST/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.7/lib/elasticsearch/transport/client.rb:115:in `perform_request'
/opt/elk/TEST/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.7/lib/elasticsearch/api/actions/search.rb:159:in `search'
/opt/elk/TEST/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-input-elasticsearch-0.1.5/lib/logstash/inputs/elasticsearch.rb:146:in `run'
/opt/elk/TEST/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/pipeline.rb:177:in `inputworker'
/opt/elk/TEST/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/pipeline.rb:171:in `start_input' {:level=>:error, :file=>"logstash/pipeline.rb", :line=>"182", :method=>"inputworker"}
org/jruby/RubyIO.java:2858:in `read_nonblock'
/opt/elk/TEST/logstash-1.5.0/vendor/jruby/lib/ruby/1.9/net/protocol.rb:141:in `rbuf_fill'
/opt/elk/TEST/logstash-1.5.0/vendor/jruby/lib/ruby/1.9/net/protocol.rb:122:in `readuntil'
/opt/elk/TEST/logstash-1.5.0/vendor/jruby/lib/ruby/1.9/net/protocol.rb:132:in `readline'
/opt/elk/TEST/logstash-1.5.0/vendor/jruby/lib/ruby/1.9/net/http.rb:2571:in `read_status_line'
/opt/elk/TEST/logstash-1.5.0/vendor/jruby/lib/ruby/1.9/net/http.rb:2560:in `read_new'
/opt/elk/TEST/logstash-1.5.0/vendor/jruby/lib/ruby/1.9/net/http.rb:1328:in `transport_request'
org/jruby/RubyKernel.java:1270:in `catch'
/opt/elk/TEST/logstash-1.5.0/vendor/jruby/lib/ruby/1.9/net/http.rb:1325:in `transport_request'
/opt/elk/TEST/logstash-1.5.0/vendor/jruby/lib/ruby/1.9/net/http.rb:1302:in `request'
/opt/elk/TEST/logstash-1.5.0/vendor/jruby/lib/ruby/1.9/net/http.rb:1295:in `request'
/opt/elk/TEST/logstash-1.5.0/vendor/jruby/lib/ruby/1.9/net/http.rb:746:in `start'
/opt/elk/TEST/logstash-1.5.0/vendor/jruby/lib/ruby/1.9/net/http.rb:1293:in `request'
/opt/elk/TEST/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:82:in `perform_request'
/opt/elk/TEST/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:40:in `call'
/opt/elk/TEST/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
/opt/elk/TEST/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:32:in `call'
/opt/elk/TEST/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
/opt/elk/TEST/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
/opt/elk/TEST/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.7/lib/elasticsearch/transport/transport/http/faraday.rb:24:in `perform_request'
org/jruby/RubyProc.java:271:in `call'
/opt/elk/TEST/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.7/lib/elasticsearch/transport/transport/base.rb:187:in `perform_request'
/opt/elk/TEST/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.7/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
/opt/elk/TEST/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.7/lib/elasticsearch/transport/client.rb:115:in `perform_request'
/opt/elk/TEST/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.7/lib/elasticsearch/api/actions/search.rb:159:in `search'
/opt/elk/TEST/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-input-elasticsearch-0.1.5/lib/logstash/inputs/elasticsearch.rb:146:in `run'
/opt/elk/TEST/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/pipeline.rb:177:in `inputworker'
/opt/elk/TEST/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/pipeline.rb:171:in `start_input'
Plugin is finished {:plugin=><LogStash::Inputs::Elasticsearch hosts=>[{:host=>"w530", :port=>9200, :protocol=>"http"}], index=>"logstash-*", query=>"{\"query\": { \"match_all\": {} } }", scroll=>"1m", docinfo_target=>"@metadata", docinfo_fields=>["_index", "_type", "_id"]>, :level=>:info, :file=>"logstash/plugin.rb", :line=>"61", :method=>"finished"}
^CSIGINT received. Shutting down the pipeline. {:level=>:warn, :file=>"logstash/agent.rb", :line=>"116", :method=>"execute"}
Sending shutdown signal to input thread {:thread=>#<Thread:0xd0578df sleep>, :level=>:info, :file=>"logstash/pipeline.rb", :line=>"258", :method=>"shutdown"}
Plugin is finished {:plugin=><LogStash::Outputs::Stdout >, :level=>:info, :file=>"logstash/plugin.rb", :line=>"61", :method=>"finished"}
Pipeline shutdown complete. {:level=>:info, :file=>"logstash/pipeline.rb", :line=>"100", :method=>"run"}
Logstash shutdown completed
LogStash::ShutdownSignal: LogStash::ShutdownSignal
        sleep at org/jruby/RubyKernel.java:834
  inputworker at /opt/elk/TEST/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/pipeline.rb:195
  start_input at /opt/elk/TEST/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/pipeline.rb:171
abonuccelli@w530 /opt/elk/TEST/logstash-1.5.0 $ 
```

same config (except different host parameter name) works in 1.4.2 in same setup

config

```
abonuccelli@w530 /opt/elk/TEST/logstash-1.4.2 $ cat config/9661.conf 
input { 
    elasticsearch {  
            host => "w530" 
            index => "test"
            port => "9203"
    } 
}

filter {

}
output {
    stdout{ codec=>rubydebug }
}
```

run

```
abonuccelli@w530 /opt/elk/TEST/logstash-1.4.2 $ ./bin/logstash -f config/9661.conf  --debug
Reading config file {:file=>"logstash/agent.rb", :level=>:debug, :line=>"301"}
Compiled pipeline code:
@inputs = []
@filters = []
@outputs = []
@input_elasticsearch_1 = plugin("input", "elasticsearch", LogStash::Util.hash_merge_many({ "host" => ("w530".force_encoding("UTF-8")) }, { "index" => ("test".force_encoding("UTF-8")) }, { "port" => ("9203".force_encoding("UTF-8")) }))

@inputs << @input_elasticsearch_1

@output_stdout_3 = plugin("output", "stdout", LogStash::Util.hash_merge_many({ "codec" => ("rubydebug".force_encoding("UTF-8")) }))

@outputs << @output_stdout_3
  @filter_func = lambda do |event, &block|
    extra_events = []
    @logger.debug? && @logger.debug("filter received", :event => event.to_hash)
    newevents = []
    extra_events.each do |event|
      @filter_mutate_2.filter(event) do |newevent|
        newevents << newevent
      end
    end
    extra_events += newevents
    @filter_mutate_2.filter(event) do |newevent|
      extra_events << newevent
    end
    if event.cancelled?
      extra_events.each(&block)
      return
    end

    extra_events.each(&block)
  end
  @output_func = lambda do |event, &block|
    @logger.debug? && @logger.debug("output received", :event => event.to_hash)
    @output_stdout_3.handle(event)

  end {:level=>:debug, :file=>"logstash/pipeline.rb", :line=>"26"}
Using milestone 1 input plugin 'elasticsearch'. This plugin should work, but would benefit from use by folks like you. Please let us know if you find bugs or have suggestions on how to improve this plugin.  For more information on plugin milestones, see http://logstash.net/docs/1.4.2/plugin-milestones {:level=>:warn, :file=>"logstash/config/mixin.rb", :line=>"209"}
config LogStash::Codecs::JSON/@charset = "UTF-8" {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Inputs::Elasticsearch/@host = "w530" {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Inputs::Elasticsearch/@index = "test" {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Inputs::Elasticsearch/@port = 9203 {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Inputs::Elasticsearch/@debug = false {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Inputs::Elasticsearch/@codec = <LogStash::Codecs::JSON charset=>"UTF-8"> {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Inputs::Elasticsearch/@add_field = {} {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Inputs::Elasticsearch/@query = "*" {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Inputs::Elasticsearch/@scan = true {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Inputs::Elasticsearch/@size = 1000 {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Inputs::Elasticsearch/@scroll = "1m" {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Filters::Mutate/@add_field = {"_id"=>"%{[@metadata][_id]}"} {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Filters::Mutate/@type = "" {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Filters::Mutate/@tags = [] {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Filters::Mutate/@exclude_tags = [] {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Filters::Mutate/@add_tag = [] {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Filters::Mutate/@remove_tag = [] {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Filters::Mutate/@remove_field = [] {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Outputs::Stdout/@codec = <LogStash::Codecs::RubyDebug > {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Outputs::Stdout/@type = "" {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Outputs::Stdout/@tags = [] {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Outputs::Stdout/@exclude_tags = [] {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Outputs::Stdout/@workers = 1 {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
Pipeline started {:level=>:info, :file=>"logstash/pipeline.rb", :line=>"78"}
filter received {:event=>{"field"=>"value", "@version"=>"1", "@timestamp"=>"2015-05-19T12:34:02.304Z"}, :level=>:debug, :file=>"(eval)", :line=>"15"}
filters/LogStash::Filters::Mutate: adding value to field {:field=>"_id", :value=>["%{[@metadata][_id]}"], :level=>:debug, :file=>"logstash/filters/base.rb", :line=>"168"}
output received {:event=>{"field"=>"value", "@version"=>"1", "@timestamp"=>"2015-05-19T12:34:02.304Z", "@metadata"=>{}, "_id"=>"%{[@metadata][_id]}"}, :level=>:debug, :file=>"(eval)", :line=>"34"}
Plugin is finished {:plugin=><LogStash::Inputs::Elasticsearch host=>"w530", index=>"test", query=>"*", scroll=>"1m">, :level=>:info, :file=>"logstash/plugin.rb", :line=>"59"}
Plugin is finished {:plugin=><LogStash::Filters::Mutate add_field=>{"_id"=>"%{[@metadata][_id]}"}>, :level=>:info, :file=>"logstash/plugin.rb", :line=>"59"}{
         "field" => "value",
      "@version" => "1",
    "@timestamp" => "2015-05-19T12:34:02.304Z",
}

Plugin is finished {:plugin=><LogStash::Outputs::Stdout >, :level=>:info, :file=>"logstash/plugin.rb", :line=>"59"}
Pipeline shutdown complete. {:level=>:info, :file=>"logstash/pipeline.rb", :line=>"89"}
```

**Comment by jordansissel** [comment]
Closing due to age - 1.5.0 is not supported anymore. Open a new issue if this happens again.
