### ISSUE TITLE
custom user agent no longer set since LS 7.16

### ISSUE THREAD

**Issue by kares** [logstash-plugins/logstash-input-elasticsearch#167]
This is a regression with the Elasticsearch(-transport) gem.

Versions 7.14 / 7.15 work as expected but 7.16 and 7.17 started failing and keep using the default header.
Upstream issue: https://github.com/elastic/elasticsearch-ruby/issues/1684

The issue reproduces in CI when running specs:
```
Failures:

  1) LogStash::Inputs::Elasticsearch client 'user-agent' header used by plugin client should sent the expect user-agent
     Failure/Error: expect(request.header['user-agent'][0]).to match(/logstash\/\d*\.\d*\.\d* \(OS=.*; JVM=.*\) logstash-input-elasticsearch\/\d*\.\d*\.\d*/)
     
       expected "elasticsearch-ruby/7.17.0 (RUBY_VERSION: 9.2.20.0; linux x86_64; Manticore 0.8.0)" to match /logstash\/\d*\.\d*\.\d* \(OS=.*; JVM=.*\) logstash-input-elasticsearch\/\d*\.\d*\.\d*/
       Diff:
       @@ -1 +1 @@
       -/logstash\/\d*\.\d*\.\d* \(OS=.*; JVM=.*\) logstash-input-elasticsearch\/\d*\.\d*\.\d*/
       +"elasticsearch-ruby/7.17.0 (RUBY_VERSION: 9.2.20.0; linux x86_64; Manticore 0.8.0)"
       
     # ./spec/inputs/elasticsearch_spec.rb:874:in `block in <main>'
     # /opt/local/rvm/gems/jruby-9.2.20.0@ls/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in <main>'
     # /opt/local/rvm/gems/jruby-9.2.20.0@ls/gems/logstash-devutils-2.3.0-java/lib/logstash/devutils/rspec/spec_helper.rb:61:in `block in <main>'

Finished in 2.3 seconds (files took 6.95 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./spec/inputs/elasticsearch_spec.rb:865 # LogStash::Inputs::Elasticsearch client 'user-agent' header used by plugin client should sent the expect user-agent
```
---

The issue also affects ES filter: https://github.com/logstash-plugins/logstash-filter-elasticsearch/issues/157

**Comment by andsel** [comment]
Published with version https://github.com/logstash-plugins/logstash-input-elasticsearch/tree/v4.12.3
