### ISSUE TITLE
failing specs under ng-pipeline

### ISSUE THREAD

**Issue by colinsurprenant** [logstash-plugins/logstash-input-elasticsearch#37]
@andrewvc these specs failures seems related to ng-pipeline under master.

```
Using Accessor#strict_set for specs
Run options: exclude {:redis=>true, :socket=>true, :performance=>true, :couchdb=>true, :elasticsearch=>true, :elasticsearch_secure=>true, :export_cypher=>true, :integration=>true, :windows=>true}
FFFFF.FF.

Failures:

  1) LogStash::Inputs::Elasticsearch should retrieve json event from elasticseach with scan
     Failure/Error: Unable to find matching line from backtrace
     NoMethodError:
       undefined method `each' for nil:NilClass
     # ./logstash-core/lib/logstash/pipeline.rb:258:in `output_batch'
     # ./logstash-core/lib/logstash/pipeline.rb:255:in `output_batch'
     # ./logstash-core/lib/logstash/pipeline.rb:200:in `worker_loop'
     # ./logstash-core/lib/logstash/pipeline.rb:169:in `start_workers'

  2) LogStash::Inputs::Elasticsearch should retrieve json event from elasticseach
     Failure/Error: Unable to find matching line from backtrace
     NoMethodError:
       undefined method `each' for nil:NilClass
     # ./logstash-core/lib/logstash/pipeline.rb:258:in `output_batch'
     # ./logstash-core/lib/logstash/pipeline.rb:255:in `output_batch'
     # ./logstash-core/lib/logstash/pipeline.rb:200:in `worker_loop'
     # ./logstash-core/lib/logstash/pipeline.rb:169:in `start_workers'

  3) LogStash::Inputs::Elasticsearch with Elasticsearch document information when not defining the docinfo should keep the document information in the root of the event
     Failure/Error: Unable to find matching line from backtrace
     NoMethodError:
       undefined method `each' for nil:NilClass
     # ./logstash-core/lib/logstash/pipeline.rb:258:in `output_batch'
     # ./logstash-core/lib/logstash/pipeline.rb:255:in `output_batch'
     # ./logstash-core/lib/logstash/pipeline.rb:200:in `worker_loop'
     # ./logstash-core/lib/logstash/pipeline.rb:169:in `start_workers'

  4) LogStash::Inputs::Elasticsearch with Elasticsearch document information when defining docinfo merges the values if the `docinfo_target` already exist in the `_source` document
     Failure/Error: Unable to find matching line from backtrace
     NoMethodError:
       undefined method `each' for nil:NilClass
     # ./logstash-core/lib/logstash/pipeline.rb:258:in `output_batch'
     # ./logstash-core/lib/logstash/pipeline.rb:255:in `output_batch'
     # ./logstash-core/lib/logstash/pipeline.rb:200:in `worker_loop'
     # ./logstash-core/lib/logstash/pipeline.rb:169:in `start_workers'

  5) LogStash::Inputs::Elasticsearch with Elasticsearch document information when defining docinfo should move the document information to the specified field
     Failure/Error: Unable to find matching line from backtrace
     NoMethodError:
       undefined method `each' for nil:NilClass
     # ./logstash-core/lib/logstash/pipeline.rb:258:in `output_batch'
     # ./logstash-core/lib/logstash/pipeline.rb:255:in `output_batch'
     # ./logstash-core/lib/logstash/pipeline.rb:200:in `worker_loop'
     # ./logstash-core/lib/logstash/pipeline.rb:169:in `start_workers'

  6) LogStash::Inputs::Elasticsearch with Elasticsearch document information when defining docinfo should move the document info to the @metadata field
     Failure/Error: Unable to find matching line from backtrace
     NoMethodError:
       undefined method `each' for nil:NilClass
     # ./logstash-core/lib/logstash/pipeline.rb:258:in `output_batch'
     # ./logstash-core/lib/logstash/pipeline.rb:255:in `output_batch'
     # ./logstash-core/lib/logstash/pipeline.rb:200:in `worker_loop'
     # ./logstash-core/lib/logstash/pipeline.rb:169:in `start_workers'

  7) LogStash::Inputs::Elasticsearch with Elasticsearch document information when defining docinfo should allow to specify which fields from the document info to save to the @metadata field
     Failure/Error: Unable to find matching line from backtrace
     NoMethodError:
       undefined method `each' for nil:NilClass
     # ./logstash-core/lib/logstash/pipeline.rb:258:in `output_batch'
     # ./logstash-core/lib/logstash/pipeline.rb:255:in `output_batch'
     # ./logstash-core/lib/logstash/pipeline.rb:200:in `worker_loop'
     # ./logstash-core/lib/logstash/pipeline.rb:169:in `start_workers'

Finished in 1.45 seconds (files took 1.35 seconds to load)
9 examples, 7 failures

Failed examples:

rspec /Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-input-elasticsearch/spec/inputs/elasticsearch_spec.rb:77 # LogStash::Inputs::Elasticsearch should retrieve json event from elasticseach with scan
rspec /Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-input-elasticsearch/spec/inputs/elasticsearch_spec.rb:26 # LogStash::Inputs::Elasticsearch should retrieve json event from elasticseach
rspec /Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-input-elasticsearch/spec/inputs/elasticsearch_spec.rb:297 # LogStash::Inputs::Elasticsearch with Elasticsearch document information when not defining the docinfo should keep the document information in the root of the event
rspec /Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-input-elasticsearch/spec/inputs/elasticsearch_spec.rb:192 # LogStash::Inputs::Elasticsearch with Elasticsearch document information when defining docinfo merges the values if the `docinfo_target` already exist in the `_source` document
rspec /Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-input-elasticsearch/spec/inputs/elasticsearch_spec.rb:251 # LogStash::Inputs::Elasticsearch with Elasticsearch document information when defining docinfo should move the document information to the specified field
rspec /Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-input-elasticsearch/spec/inputs/elasticsearch_spec.rb:241 # LogStash::Inputs::Elasticsearch with Elasticsearch document information when defining docinfo should move the document info to the @metadata field
rspec /Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-input-elasticsearch/spec/inputs/elasticsearch_spec.rb:272 # LogStash::Inputs::Elasticsearch with Elasticsearch document information when defining docinfo should allow to specify which fields from the document info to save to the @metadata field

Randomized with seed 59991
```

**Comment by andrewvc** [comment]
Thanks @colinsurprenant looking into it

**Comment by andrewvc** [comment]
Fixed in https://github.com/elastic/logstash/commit/1cbe279d11857761f6f175128f49183cfdf6b4a9
