### ISSUE TITLE
JRUBY 9K faillures

### ISSUE THREAD

**Issue by ph** [logstash-plugins/logstash-input-elasticsearch#70]
```
document info to the @metadata field
     Failure/Error: (output_func(event) || []).each do |output|
     
     NoMethodError:
       undefined method `each' for #<Queue:0x23c72128>
     # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/logstash-core-5.4.0-java/lib/logstash/pipeline.rb:400:in `block in output_batch'
     # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/logstash-core-5.4.0-java/lib/logstash/util/wrapped_synchronous_queue.rb:224:in `block in each'
     # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/logstash-core-5.4.0-java/lib/logstash/util/wrapped_synchronous_queue.rb:223:in `each'
     # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/logstash-core-5.4.0-java/lib/logstash/pipeline.rb:394:in `output_batch'
     # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/logstash-core-5.4.0-java/lib/logstash/pipeline.rb:352:in `worker_loop'
     # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/logstash-core-5.4.0-java/lib/logstash/pipeline.rb:317:in `block in start_workers'
  4) LogStash::Inputs::Elasticsearch with Elasticsearch document information when defining docinfo merges the values if the `docinfo_target` already exist in the `_source` document
     Failure/Error: (output_func(event) || []).each do |output|
     
     NoMethodError:
       undefined method `each' for #<Queue:0x6eb00cbe>
     # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/logstash-core-5.4.0-java/lib/logstash/pipeline.rb:400:in `block in output_batch'
     # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/logstash-core-5.4.0-java/lib/logstash/util/wrapped_synchronous_queue.rb:224:in `block in each'
     # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/logstash-core-5.4.0-java/lib/logstash/util/wrapped_synchronous_queue.rb:223:in `each'
     # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/logstash-core-5.4.0-java/lib/logstash/pipeline.rb:394:in `output_batch'
     # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/logstash-core-5.4.0-java/lib/logstash/pipeline.rb:352:in `worker_loop'
     # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/logstash-core-5.4.0-java/lib/logstash/pipeline.rb:317:in `block in start_workers'
  5) LogStash::Inputs::Elasticsearch with Elasticsearch document information when defining docinfo should move the document information to the specified field
     Failure/Error: (output_func(event) || []).each do |output|
     
     NoMethodError:
       undefined method `each' for #<Queue:0xc30f26d>
     # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/logstash-core-5.4.0-java/lib/logstash/pipeline.rb:400:in `block in output_batch'
     # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/logstash-core-5.4.0-java/lib/logstash/util/wrapped_synchronous_queue.rb:224:in `block in each'
     # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/logstash-core-5.4.0-java/lib/logstash/util/wrapped_synchronous_queue.rb:223:in `each'
     # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/logstash-core-5.4.0-java/lib/logstash/pipeline.rb:394:in `output_batch'
     # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/logstash-core-5.4.0-java/lib/logstash/pipeline.rb:352:in `worker_loop'
     # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/logstash-core-5.4.0-java/lib/logstash/pipeline.rb:317:in `block in start_workers'
  6) LogStash::Inputs::Elasticsearch with Elasticsearch document information when defining docinfo should allow to specify which fields from the document info to save to the @metadata field
     Failure/Error: (output_func(event) || []).each do |output|
     
     NoMethodError:
       undefined method `each' for #<Queue:0x16944b58>
     # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/logstash-core-5.4.0-java/lib/logstash/pipeline.rb:400:in `block in output_batch'
     # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/logstash-core-5.4.0-java/lib/logstash/util/wrapped_synchronous_queue.rb:224:in `block in each'
     # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/logstash-core-5.4.0-java/lib/logstash/util/wrapped_synchronous_queue.rb:223:in `each'
     # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/logstash-core-5.4.0-java/lib/logstash/pipeline.rb:394:in `output_batch'
     # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/logstash-core-5.4.0-java/lib/logstash/pipeline.rb:352:in `worker_loop'
     # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/logstash-core-5.4.0-java/lib/logstash/pipeline.rb:317:in `block in start_workers'

**Comment by yaauie** [comment]
Closing; we've been running on JRuby 9k since 6.0, and no longer exhibit these symptoms.
